version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    restart: always

  mysqld-exporter-master:
    image: prom/mysqld-exporter:v0.14.0
    container_name: mysqld-exporter-master
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=exporter:123456!23Qaz.@tcp(172.16.28.60:3306)/
    restart: always
    networks:
      - monitor-net

  mysqld-exporter-slave:
    image: prom/mysqld-exporter:v0.14.0
    container_name: mysqld-exporter-slave
    ports:
      - "9105:9104"
    environment:
      - DATA_SOURCE_NAME=exporter:123456!23Qaz.@tcp(172.16.28.63:3306)/
    restart: always
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./prometheus/alertmanager.tmpl:/etc/alertmanager/template/alertmanager.tmpl
    restart: always
    networks:
      - monitor-net

  prometheus-webhook-dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: webhook-dingtalk
    ports:
      - "8060:8060"
    volumes:
      - ./prometheus/dingtalk.yml:/etc/prometheus-webhook-dingtalk/config.yml
      - ./prometheus/alertmanager.tmpl:/etc/prometheus-webhook-dingtalk/templates/alertmanager.tmpl
    command:
      - "--config.file=/etc/prometheus-webhook-dingtalk/config.yml"
    restart: always
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
