global:
  resolve_timeout: 30s

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  receiver: "dingtalk-webhook"
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  group_by: ["alertname", "instance"]

  routes:
    - match:
        severity: critical
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 2m

    - match:
        severity: warning
      group_wait: 5s
      group_interval: 2m
      repeat_interval: 10m

receivers:
  - name: "dingtalk-webhook"
    webhook_configs:
      - url: "http://prometheus-webhook-dingtalk:8060/dingtalk/webhook/send"
        send_resolved: true
