global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093' 

scrape_configs:
  - job_name: 'mysql_master'
    static_configs:
      - targets: ['mysqld-exporter-master:9104']
        labels:
          instance: 'master'

  - job_name: 'mysql_slave'
    static_configs:
      - targets: ['mysqld-exporter-slave:9104']
        labels:
          instance: 'slave'
